remote:
  host: 192.168.124.28
  # defaults
  # port: 22
  # username: fedora
  # password: supersecret # RECOMMENDED: use pkey auth instead
  # pkey: ~/.ssh/id_rsa
  pkey: ~/.ssh/kvm

metal:
  vm:
    pid: 2093543

prometheus:
  url: http://localhost:9090


