BIND_ADDRESS: 0.0.0.0:9103
CGROUP_METRICS: '*'
CPU_ARCH_OVERRIDE: ""
ENABLE_EBPF_CGROUPID: "true"
ENABLE_GPU: "true" # -> false
ENABLE_PROCESS_METRICS: "true"
ENABLE_QAT: "false"
EXPOSE_CGROUP_METRICS: "true"
EXPOSE_HW_COUNTER_METRICS: "true"
EXPOSE_IRQ_COUNTER_METRICS: "true"
EXPOSE_KUBELET_METRICS: "true"
KEPLER_LOG_LEVEL: "5"
KEPLER_NAMESPACE: kepler-operator
METRIC_PATH: /metrics
MODEL_CONFIG: |
  NODE_TOTAL_ESTIMATOR=true
  NODE_TOTAL_INIT_URL=https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.7/specpower/acpi/AbsPower/BPFOnly/GradientBoostingRegressorTrainer_0.zip
  NODE_COMPONENTS_ESTIMATOR=true
  NODE_COMPONENTS_INIT_URL=https://raw.githubusercontent.com/sustainable-computing-io/kepler-model-db/main/models/v0.7/ec2/intel_rapl/AbsPower/BPFOnly/GradientBoostingRegressorTrainer_0.zip
MODEL_SERVER_ENABLE: "true"
MODEL_SERVER_URL: http://kepler-model-server-svc.kepler-operator.svc.cluster.local:8100
